config/routes.rb
Rails.application.routes.draw do
  root 'memos#index'
  resources :memos
  resources :places

end

app/models/form.rb
module Form
  def self.table_name_prefix
    'form_'
  end
end

app/models/form/memo.rb
class Form::Memo < Memo
  REGISTRABLE_ATTRIBUTES = %i(name)
  has_many :places, class_name: 'Form::Place'

  after_initialize { places.build unless self.persisted? || places.present? }

end

app/models/form/place.rb
class Form::Place < Place
  REGISTRABLE_ATTRIBUTES = %i(id title description address latitude longitude _destroy)
end

app/models/memo.rb
class Memo < ActiveRecord::Base
  has_many :places, dependent: :destroy
  accepts_nested_attributes_for :places, allow_destroy: true

  validates :name,  presence: true, length: { maximum: 50 }
end

app/models/place.rb
class Place < ActiveRecord::Base
  belongs_to :memo
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :name,  presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, format: { with: VALID_EMAIL_REGEX },
    uniqueness: { case_sensitive: false }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/memos_controller.rb
class MemosController < ApplicationController
  before_action :correct_memo,    only: [:edit, :update] 

  def index
    @memo_items = Memo.all
  end

  def new
    @memo = Form::Memo.new
  end

  def create
    @memo = Form::Memo.new(memo_params)
    if @memo.save
      redirect_to memos_path, notice: "Created #{@memo.name} "
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @memo.update_attributes(memo_params)
      redirect_to memos_path, notice: "Updated #{@memo.name} "
    else
      render :edit
    end
  end

  def destroy

  end

  private

  def memo_params
    params
    .require(:form_memo)
    .permit(
      Form::Memo::REGISTRABLE_ATTRIBUTES +
      [places_attributes: Form::Place::REGISTRABLE_ATTRIBUTES]
    )
  end

  def correct_memo
    @memo = Form::Memo.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/memos_helper.rb
module MemosHelper
end

app/views/layouts/_footer.html.erb
<footer class="page-footer blue lighten-2">
  <div class="container">
    <div class="row">
      <div class="col l6 s12">
        <h5 class="white-text">Footer Content</h5>
        <p class="grey-text text-lighten-4">You can use rows and columns here to organize your footer content.</p>
      </div>
      <div class="col l4 offset-l2 s12">
        <h5 class="white-text">Links</h5>
        <ul>
          <li><a class="grey-text text-lighten-3" href="#!">Link 1</a></li>
          <li><a class="grey-text text-lighten-3" href="#!">Link 2</a></li>
          <li><a class="grey-text text-lighten-3" href="#!">Link 3</a></li>
          <li><a class="grey-text text-lighten-3" href="#!">Link 4</a></li>
        </ul>
      </div>
    </div>
  </div>
  <div class="footer-copyright">
    <div class="container">
      © 2014 Copyright Text
      <a class="grey-text text-lighten-4 right" href="#!">More Links</a>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<nav class="blue lighten-2">
  <div class="nav-wrapper">
    <a href="#!" class="brand-logo center">placememo</a>
    <a href="#" data-activates="mobile-demo" class="button-collapse"><i class="mdi-navigation-menu"></i></a>
    <ul class="right hide-on-med-and-down">
      <%= link_to memos_path, data: { no_turbolink: true } do %>
        <i class="mdi-action-home"></i>
      <% end %>
      <%= link_to new_memo_path, data: { no_turbolink: true } do %>
        <i class="mdi-content-add-box"></i>
      <% end %>
    </ul>
    <ul class="side-nav" id="mobile-demo">
      <li><a href="#">Home</a></li>
      <li><a href="#">Search</a></li>
      <li><a href="#">Setting</a></li>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Placememo</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/header' %>
<% unless yield(:title).blank?  %>
  <%= render partial: 'shared/title', locals: {title: yield(:title)} %>
<% end %>
<%= yield %>
<%= render 'layouts/footer' %>
</body>
</html>

app/views/memos/_form.html.erb
<%= form_for(@memo, url: path, method: method) do |f| %>
  <div class="row"></div>
  <div class="row">
    <div class="input-field col s11">
      <%= f.text_field :name, class: '' %>
      <%= f.label :name, 'Memo Name' %>
    </div>
  </div>

  <div class="row">
    <%= button_tag :type=> "submit", :class => "btn waves-effect waves-light" do %>
      Save
    <% end %>
    <%= link_to_add_association f, :places, 
      class: 'waves-effect waves-light btn',
      data: {
        association_insertion_node: '#memo_detail_places',
        association_insertion_method: 'prepend' } do %>
        Add Place
    <% end %>
  </div>
  <div class="row"></div>

  <div id="memo_detail_places">
    <%= f.fields_for :places do |p| %>
      <%= render 'place_fields', f: p %>
    <% end %>
  </div>

<% end %>

app/views/memos/_place_fields.html.erb
<ul class="collapsible nested-fields" >
  <li>
  <div class="collapsible-header active blue lighten-5">Place</div>
  <div class="collapsible-body">
    <div class="row"></div>
    <%= f.hidden_field :id %>
    <%= f.hidden_field :latitude %>
    <%= f.hidden_field :longitude %>
    <div class="row">
      <div class="input-field col s11">
        <%= f.text_field :title, class: '' %>
        <%= f.label :title, 'Title' %>
      </div>
    </div>
    <div class="row">
      <div class="input-field col s11">
        <%= f.text_field :description, class: '' %>
        <%= f.label :description, 'Description' %>
      </div>
    </div>
    <div class="row">
      <div class="input-field col s11">
        <%= f.text_field :address, class: 'address', placeholder: 'Enter the address' %>
        <%= f.label :address, 'Address' %>
      </div>
    </div>
    <div class="row right-align">
      <div class="col s11">
        <%= link_to_remove_association f, class: 'btn waves-effect waves-light' do %>
          <i class="mdi-action-delete"></i>
      <% end %>
      </div>
    </div>
  </div>
  </li>
</ul>

app/views/memos/edit.html.erb
<% provide(:title, 'Edit Memo') %>

<div class="row">
  <div id="contents" class="col s12 m6 l6">
    <%= render 'form', path: memo_path, method: :put %>
  </div>

  <div id="map_for_search" class="col s12 m6 l6">
    <div id="map_canvas" style="width:100%;height:500px;"></div>
  </div>
</div>

<script src="//maps.googleapis.com/maps/api/js?v=3.exp&sensor=true&libraries=places"></script>
<%= javascript_include_tag 'memos' %>

app/views/memos/index.html.erb
<% provide(:title, 'Memo Collection') %>
<div>
  <%= render 'shared/message' %>
  <%= render 'shared/memo' %>
</div>

app/views/memos/new.html.erb
<% provide(:title, 'Create Memo') %>

<div class="row">
  <div id="contents" class="col s12 m6 l6">
    <%= render 'form', path: memos_path, method: :post %>
  </div>

  <div id="map_for_search" class="col s12 m6 l6">
    <div id="map_canvas" style="width:100%;height:500px;"></div>
  </div>
</div>

<script src="//maps.googleapis.com/maps/api/js?v=3.exp&sensor=true&libraries=places"></script>
<%= javascript_include_tag 'memos' %>

app/views/shared/_memo.html.erb
<% if @memo_items.any? %>
  <% @memo_items.each_slice(4) do |memos| %>
  <div class="row">
    <%= render partial: 'shared/memo_item', collection: memos, as: :memo %>
  </div>  
  <% end %>
<% end %>

app/views/shared/_memo_item.html.erb
<div class="col s12 m6 l3">
  <div id="<%= memo.id %>" class="card blue lighten-4">
    <div class="card-image waves-effect waves-block waves-light">
      <%= image_tag 'map.jpg' %>
    </div>
    <div class="card-content grey-text text-darken-2">
      <%= link_to edit_memo_path(memo.id), class: "card-title grey-text text-darken-2", data: { no_turbolink: true } do %>
        <%= memo.name%>
      <% end %>
      <p><%= memo.explanation %></p>
    </div>
  </div>
</div>

app/views/shared/_message.html.erb
<% if notice then %>
<div class="row">
  <div class="col s12">
    <div class="card-panel yellow lighten-4">
      <span class=""><%= notice %></span>
    </div>
  </div>
</div>
<% end %>

app/views/shared/_title.html.erb
<div class="row">
  <div class="col s12 center">
    <div class="section">
      <h5><%= title %></h5>
    </div>
    <div class="divider"></div>
  </div>
</div>